# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "client<llm> GPT4oMini {\n  provider openai\n  options {\n    model \"gpt-4o-mini\"\n    api_key env.OPENAI_API_KEY\n  }\n}",
    "function.baml": "class Response {\n  @@dynamic\n}\n\nfunction BamlFunction(prompt: string) -> Response {\n  client GPT4oMini\n  prompt #\"\n    {{ prompt }}\n\n    {{ctx.output_format}}\n  \"#\n}\n\ntest Test {\n  functions [BamlFunction]\n  type_builder {\n    class Greet {\n      greeting string\n    }\n    class Depart {\n      departure_time string\n      message string\n    }\n    dynamic class Response {\n      tool_call Greet | Depart\n    }\n  }\n  args {\n    prompt #\"Greet me? My name is Greg\"#\n  }\n}",
    "generators.baml": "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"python/pydantic\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../baml_client\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.202.1\"\n\n    // Valid values: \"sync\", \"async\"\n    // This controls what `b.FunctionName()` will be (sync or async).\n    default_client_mode sync\n}\n",
}

def get_baml_files():
    return _file_map